*      Include file skelname
*
* begin_doc
*
*  RCS(Id)
*
*  RCS(Log)
*
*  Documentation for include file skelname
*
*  Purpose:
*  --------
*
*  Used in routines:
*  ----------------
*
*  Notes:
*  ------
*
*  Author:   John Doe      Created:  day-mon-xx
*  -------
*
*  Major revisions:
*  ----------------
*
* end_doc
*
*
*  Remember NO NESTED INCLUDES (except for parameters)
*
*  COMMON BLOCK NAME should be the same as include file name!
*
* begin_var
*  variables for include file skelname:
*  -----------------------------------
*
*----6----------------------------------------------------------------72
*  
*  Variables contained in skelname common block
*  --------------------------------------------
*
* end_var
*
       COMMON/skelname/
*----6----------------------------------------------------------------72

       SAVE /skelname/



