# -*- Makefile -*-
###
#
# Section of Makefile change by 'configure'
# You do not need to change this part!
#
##


# If you use configure, set this to the name of the guarded Makefile
GUARD_MAKEFILE=

## Any LOCAL area setup?
ifneq (none,$(LOCAL_LIBS)none)
LOCALLIBS = $(LIBPATHSEP)$$LOCAL_LIBS
endif

# configure parameters
cxx_root_transform=s/x/x/
java_root_transform=s/x/x/
#
CC=cc
CXX=c++
LDXX=$(DO_QUANTIFY) $(DO_PURIFY) ${CXX}
LD=
NM=nm
SYSLIBS=
JAVACIDL=@JAVACIDL@
JIDLFLAGS=@JIDLFLAGS@
JAVAC=@JAVAC@
JAVAHELP_INDEXER=@JAVAHELP_INDEXER@
HAVE_JAVAHELP=@HAVE_JAVAHELP@
JFLAGS=@JFLAGS@
SYSCLASSES=@SYSCLASSES@
MTCOMPILEOPTION=
MTLINKOPTION=
MTLIBS=
MTEXT=
DEBUG= 
DEBUG_OPTSW=
DEBUG_DBGSW=
DEBUG_EXT=
CFLAGS=$(EXTRADEFINES) -DHAVE_CONFIG_H    `echo $(INCLUDES) | sed '$(cxx_root_transform)'`
CXXFLAGS=$(EXTRADEFINES) -DHAVE_CONFIG_H    `echo $(INCLUDES) | sed '$(cxx_root_transform)'`
# LDFLAGS and LDXXFLAGS dont need $(EXTRADEFINES)
LDFLAGS=`echo "$(LOCALLIBS) $(LIBDIRS)" | sed '$(cxx_root_transform)'` 
LDXXFLAGS= `echo "$(LOCALLIBS) $(LIBDIRS)" | sed '$(cxx_root_transform)'` -o
RANLIB=@RANLIB@
AR=ar
AR_LINK=ar rv
AWK=gawk
MKDIRHIER=mkdirhier
FIND=find
ORBCXX=@ORBCXX@
ORBCXXFLAGS=-DHAVE_CONFIG_H `echo $(IDLINCLUDES) | sed '$(cxx_root_transform)'` @ORBCXXFLAGS@
ORBJAVA=@ORBJAVA@
ORBJAVAFLAGS=-DHAVE_CONFIG_H `echo $(IDLINCLUDES) | sed '$(cxx_root_transform)'` @ORBJAVAFLAGS@
MTORBLIB=@MTORBLIB@
SNORBLIB=@SNORBLIB@
ORBLIB=@ORBLIB@
ORBPATH=@ORBPATH@
ORBLIBPATH=@ORBLIBPATH@
#
INSTALL_PROGRAM=${INSTALL}
INSTALL_DATA=${INSTALL} -m 644
INSTALL_HEADER=${INSTALL} -m 644
INSTALL_LIBRARY=${INSTALL} -m 644
TEMPLATEDIR=none
TEMPLATELINKDIR=none
#
machsubname=x86_64-unknown-linux-gnu
CPU=unknown
b_transform=s/\/bin/\/bin\/x86_64-unknown-linux-gnu/
l_transform=s/\/lib/\/lib\/x86_64-unknown-linux-gnu/
i_transform=s/\/include/\/include\/x86_64-unknown-linux-gnu/
list_transform=s/x/x/
#
OEXT=.o
AEXT=.a
XEXT=
DOTO=$(DBGEXT).o
DOTA=$(DBGEXT).a
DOTX=$(DBGEXT)
PRELIB=lib
LINKLIBOPT=-l
GNUEXT=
OUTSWITCH=-o
CSWITCH=-c
DEPSWITCH=
PREDEPHEADER=none
LINKEXT=$(DBGEXT)
LIBPATHSEP=-L
CXXRULESLINE=\
	$(CXX) $(CXXFLAGS) $(DEBUG) $(CSWITCH) $< $(OUTSWITCH) $@
CXXRULES = $(shell echo $(CXXRULESLINE))
CRULESLINE=\
	$(CC) $(CFLAGS) $(DEBUG) $(CSWITCH) $< $(OUTSWITCH) $@
CRULES = $(shell echo $(CRULESLINE))
#
.PHONY: all clean distclean install
.SUFFIXES: .cxx .cc .c $(DOTO)  .java .class

.cxx$(DOTO):

	$(CXX) $(CXXFLAGS) $(DEBUG) $(CSWITCH) $< $(OUTSWITCH) $@

.cc$(DOTO):

	$(CXX) $(CXXFLAGS) $(DEBUG) $(CSWITCH) $< $(OUTSWITCH) $@

.c$(DOTO):

	$(CC) $(CFLAGS) $(DEBUG) $(CSWITCH) $< $(OUTSWITCH) $@

ifneq (,$(findstring $(PURIFY),yY)$(findstring $(QUANTIFY),yY))
include $(COM_GMAKE)/purify_quantify_rules.mk
endif

.o:

	$(LDXX) $(LDXXFLAGS) $@ $< $(LIBS)

.java.class:
	$(JAVAC) $(JFLAGS) $<

#
JAVAPACKAGE = @JAVAPACKAGE@
ADDEDJCLASSES = :$(src_root)/src/java:$(prefix)/classes:$(SC_CLASS):$(COM_CLASS)
JAVABASE = $(shell echo $(JAVAPACKAGE) | sed 's+\.+/+g' )
JAVALIST = $(shell echo $(SYSCLASSES) | sed '$(list_transform)' | sed '$(java_root_transform)' )
LOCALCLASSES= $(shell echo $(ADDEDJCLASSES)$(EXTRAJCLASSES) | sed '$(list_transform)' | sed '$(java_root_transform)' )
JCLASSES = $(JAVALIST)
#
IDLHEADERS=@IDLHEADERS@
IDLSOURCE=@IDLSOURCE@
IDLOBJECTS=@IDLOBJECTS@
#
LIBRARY = $(PRELIB)$(LIBNAME)$(GNUEXT)$(DOTA)
ONLINEDIRS = ${exec_prefix}/lib/x86_64-unknown-linux-gnu
#
# Override if used!
DEPFILE=none
LIBDEPFILE=none
#
IDLTRANSLATE=@IDLTRANSLATE@
IDLDEPENDFILE=@IDLDEPENDFILE@
HAVECORBA=@HAVECORBA@
INSTALLCORBA=@INSTALLCORBA@
ISEMBEDDED=notAvailable
INSTALLEMBEDDED=notAvailable
DEPFILEEMBEDDED=none
ISNOTEMBEDDED=notAvailable
INSTALLNOTEMBEDDED=notAvailable
DEPFILENOTEMBEDDED=none
HAVECRYPT=@HAVECRYPT@
INSTALLCRYPT=@INSTALLCRYPT@
#
ALLJAVA=@ALLJAVA@
INSTALLJAVA=@INSTALLJAVA@

# NT Service link objects
SERVICE_OBJ=

#
## Third Party Products ##
#

## Insight
# Special InSight commands
INSIGHT_CXX=
INSIGHT_LDXX=
INSEXT=-ins

#
# Objectivity
HAVEOBJY=@HAVEOBJY@
INSTALLOBJY=@INSTALLOBJY@
PAGE_SIZE=@OODEFAULT_PAGE_SIZE@
LOCKSERVER_HOST=@OODEFAULT_LOCKSERVER_HOST@
OONEWFD=@OONEWFD_CMD@
OODELETEFD=@OODELETEFD_CMD@
OODDLX=@OODDLX_CMD@
OOSCHEMAUPGRADE=@OOSCHEMAUPGRADE_CMD@
DDLFLAGS=@DDLFLAGS@
DDLHEADERS=@DDLHEADERS@
DDLSOURCES=@DDLSOURCES@
DDLOBJECTS=@DDLOBJECTS@
OBJY_HOME=@OBJY_HOME@
OBJYLIBPATH=@OBJYLIBPATH@
DBLIB=@DBLIB@
DBSTLLIB=@DBSTLLIB@
# BDL
HAVEBDLCLIENT=@HAVEBDLCLIENT@
HAVEBDLSERVER=@HAVEBDLSERVER@
HAVEBDLSCLIENT=@HAVEBDLSCLIENT@
HAVEBDLSSERVER=@HAVEBDLSSERVER@
INSTALLBDLCLIENT=@INSTALLBDLCLIENT@
INSTALLBDLSERVER=@INSTALLBDLSERVER@
INSTALLBDLSCLIENT=@INSTALLBDLSCLIENT@
INSTALLBDLSSERVER=@INSTALLBDLSSERVER@
STD_BASEINCS=@STD_BASEINCS@
STD_STDINCS=@STD_STDINCS@
STD_STLINCS=@STD_STLINCS@
STD_STDLIBS=@STD_STDLIBS@
BDL_STL_DEFINE=@BDL_STL_DEFINE@
BDLCOMPILE=@BDL_COMPILE_CMD@
BDLCOMPILE_SS=@BDL_COMPILE_SS_CMD@
BDLCONSTANTSCLIENTOBJECTS=@BDLCONSTANTSCLIENTOBJECTS@
BDLCONSTANTSSERVEROBJECTS=@BDLCONSTANTSSERVEROBJECTS@
BDLSNAPSHOTSCLIENTOBJECTS=@BDLSNAPSHOTSCLIENTOBJECTS@
BDLSNAPSHOTSSERVEROBJECTS=@BDLSNAPSHOTSSERVEROBJECTS@
IDLNAMES=@IDLNAMES@
BDLNAMES=@BDLNAMES@
DDLNAMES=@DDLNAMES@
CONSTANTS_DDL_PREFIX=@CONSTANTS_DDL_PREFIX@
CONSTANTS_BOOT_ID=@CONSTANTS_BOOT_ID@
CONSTANTS_BOOT_FILE=@CONSTANTS_BOOT_FILE@
CONSTANTS_SERVER_LIBNAME=@CONSTANTS_SERVER_LIBNAME@
BDLCLIENTHEADERS=@BDLCLIENTHEADERS@
BDLSERVERHEADERS=@BDLSERVERHEADERS@
BDLSERVEROBJECTS=@BDLSERVEROBJECTS@
BDLDDLHEADERS=@BDLDDLHEADERS@
BDLDDLSOURCES=@BDLDDLSOURCES@
BDLDDLOBJECTS=@BDLDDLOBJECTS@
# Dummies to prevent from being empty
CLIENTLIB=client
SERVERLIB=server
#
CLIENTHEADERS=$(BDLCLIENTHEADERS)
SERVERHEADERS=$(BDLSERVERHEADERS) $(BDLDDLHEADERS)
# $(BDLSERVERHEADERS)
CLIENTOBJECTS=$(BDLCLIENTOBJECTS)
SERVEROBJECTS=$(BDLSERVEROBJECTS)
BDLDEPENDFILE=@BDLDEPENDFILE@
DDLDEPENDFILE=@DDLDEPENDFILE@
