#!/usr/local/bin/perl
#
# $Id: mkfortproc,v 1.8 2002/10/16 18:33:57 cdj Exp $
###########################################################################
#  simple little script to make fortran processor skeletons
# 
#  execution:  mkfortproc fortranprocname  
# 
#  output:  fortranprocname/
#                         README.MyFortProc
#                         Makefile
#                         fortranprocname/fortranprocname.h
#                                       Template/
#                         Class/fortranprocname.cc
#                               fortranprocname_DONT_TOUCH.cc
#                         Fortran/
#                               fortranprocname_beginRun.F
#                               fortranprocname_endRun.F
#                               fortranprocname_event.F
#                               fortranprocname_hist_book.F
#                               fortranprocname_initialize.F
#                               fortranprocname_terminate.F         
#                         Instantiate/
#                         Doc/
#                         Test/
#  required input:
# 
#  fortranprocname = name of the processor
# 
#  optional input:
# 
#  none
# 
#  example:
#  mkfortproc MyFortProc 
#        --> write  MyFortProc/
#                         README.MyFortProc
#                         Makefile
#                         MyFortProc/MyFortProc.h
#                                       Template/
#                         Class/MyFortProc.cc
#                               MyFortProc_DONT_TOUCH.cc
#                         Fortran/
#                               MyFortProc_beginRun.F
#                               MyFortProc_endRun.F
#                               MyFortProc_event.F
#                               MyFortProc_hist_book.F
#                               MyFortProc_initialize.F
#                               MyFortProc_terminate.F         
#                         Instantiate/
#                         Doc/
#                         Test/
#  
#   the script tries to read in
#   a filename .tmpl in users HOME directory which contains the following lines
#             First : your first name
#             Last : your last name
#   if .tmpl is not found and firstname and lastname are blank the
#   enviroment variable LOGNAME is used to obtain the "real life" name
#   from the output of finger.
#
#   Enviroment variable PROC_SCRIPT may point to a directory that
#   contains the skeleton files.
#
#   mkfortproc will not overwrite existing files
#
#   Skeleton Keywords (Case matters):
#      procname  :  overwritten with routine name
#      John Doe  :  overwritten with author's name
#      day-mon-xx:  overwritten with todays date
#      RCS(key)  :  becomes $key$
#
#   author of the script: Martin Lohner
#   
###########################################################################


#  if the routine name is blank, 'h' or '?' go to help
if ($ARGV[0] !~ /\w/ 
 || $ARGV[0] eq "\?" 
 || $ARGV[0] eq "h" 
 || $ARGV[0] eq "-h" 
 || $ARGV[0] eq "-help" ) {
   &wrt_help; 
}

$author1 = "\u$ARGV[2]";
$author2 = "\u$ARGV[3]";

# environment variables
$home = $ENV{"HOME"};
$c3_inc = $ENV{"C3_INC"};
$c_gmake = $ENV{"C3_GMAKE"};

#  skeleton file directory
# eventually will use $skel_dir = $ENV{"CMH_SCRIPT"};
if (!$skel_dir) {
    $CLEO3 = $ENV{"C3_CVSSRC"};
    $skel_dir = "$CLEO3/Skeletons";
}

# get name
($name, $ext) = split(/\./, $ARGV[0]);

#create the directories
mkdir("$name", 0777) || die "can not make dir $name";
mkdir("$name/$name", 0777) || die "can not make dir $name/$name";
mkdir("$name/$name/Template", 0777) || die "can not make dir $name/$name/Template";
mkdir("$name/Class", 0777) || die "can not make dir $name/Class";
mkdir("$name/Fortran", 0777) || die "can not make dir $name/Fortran";
mkdir("$name/Instantiate", 0777) || die "can not make dir $name/Instantiate";
mkdir("$name/Test", 0777) || die "can not make dir $name/Test";
mkdir("$name/Doc", 0777) || die "can not make dir $name/Doc";

$skeleton = "$skel_dir/FortranProc/README.FortranProc";
$outfile = "$name/" . README . '.' . $name;
&make_file($skeleton, $outfile);

$skeleton = "$skel_dir/FortranProc/FortranProc.h";
$outfile = "$name/$name/" . $name . '.h';
&make_file($skeleton, $outfile);

$skeleton = "$skel_dir/FortranProc/FortranProc.cc";
$outfile = "$name/Class/" . $name . '.cc';
&make_file($skeleton, $outfile);

$skeleton = "$skel_dir/FortranProc/FortranProc_DONT_TOUCH.cc";
$outfile = "$name/Class/" . $name . '_DONT_TOUCH.cc';
&make_file($skeleton, $outfile);

$skeleton = "$skel_dir/FortranProc/FortranProc_initialize.F";
$outfile = "$name/Fortran/" . $name . '_initialize.F';
&make_file($skeleton, $outfile);

$skeleton = "$skel_dir/FortranProc/FortranProc_terminate.F";
$outfile = "$name/Fortran/" . $name . '_terminate.F';
&make_file($skeleton, $outfile);

$skeleton = "$skel_dir/FortranProc/FortranProc_hist_book.F";
$outfile = "$name/Fortran/" . $name . '_hist_book.F';
&make_file($skeleton, $outfile);

$skeleton = "$skel_dir/FortranProc/FortranProc_event.F";
$outfile = "$name/Fortran/" . $name . '_event.F';
&make_file($skeleton, $outfile);

$skeleton = "$skel_dir/FortranProc/FortranProc_beginRun.F";
$outfile = "$name/Fortran/" . $name . '_beginRun.F';
&make_file($skeleton, $outfile);

$skeleton = "$skel_dir/FortranProc/FortranProc_endRun.F";
$outfile = "$name/Fortran/" . $name . '_endRun.F';
&make_file($skeleton, $outfile);

$skeleton = "$c_gmake/M.fortproc";
$outfile = "$name/Makefile";
&copy_file($skeleton, $outfile);


# copy file
sub copy_file {
# first argument is file to be copied
$skeleton = $_[0]; 
# second argument is the name of the new file
$outfile = $_[1];

if (-s "$outfile") {
    print "mkfortproc  W: $outfile FILE ALREADY EXISTS WILL NOT OVERWRITE!!\n";
    print "mkfortproc  W: *****************************************************\n";
} else {

#   write out some stuff to the screen
    print "mkfortproc  I: copying file $skeleton to $outfile\n";

#open the skeleton file and output file
    open(IN,$skeleton)    or die "Opening $skeleton: $!\n";
    open(OUT,">$outfile") or die "Opening $outfile: $!\n";

# loop over lines in "skeleton.F" and overwrite where neccessary
    while(<IN>) {
	print OUT $_;
    }
    close(IN);   
    close(OUT);
}
}


# generate file
sub make_file {
# first argument is the skeleton file to use
$skeleton = $_[0];
# second argument is the name of the output file
$outfile = $_[1];

if (-s "$outfile") {
    print "mkfortproc  W: $outfile FILE ALREADY EXISTS WILL NOT OVERWRITE!!\n";
    print "mkfortproc  W: *****************************************************\n";
} else {
#  get the current date
    $now = `date`;
    chop($now);

# get authors name from $HOME/.tmpl file

    $afrom = "command line";
    if ($author1 eq "" && -s "$home/.tmpl") {
	open(IN,"$home/.tmpl");
	$afrom = "users .tmpl file";
	while(<IN>) {
	    if (/First\w*/) {
		@words = split(/:/, $_);
		$author1 = $words[1]; 
		chop($author1);
	    } elsif (/Last\w*/) {
		@words = split(/:/, $_);
		$author2 = $words[1];
		chop($author2);
	    }
	}
	close(IN);
	$author = "$author1 $author2";
    }
#
# if author is still blank fill it in with REAL LIFE name in finger output
#
    if ($author1 eq "") {
	$author1 = $ENV{"LOGNAME"};
	foreach $_ (`finger -m "$author1"`) {
	    if (/Login n\w*/) {
		@words = split(/: /, $_);
		$author = $words[2];
		chop($author);
		$afrom = "the output finger cmnd";
	    }
	}
    }
#   write out some stuff to the screen
    print "mkfortproc  I: using skeleton: $skeleton \n";
    print "mkfortproc  I: authors name is: $author, determined by $afrom \n";
    print "mkfortproc  I: creating file: $outfile \n";

#open the skeleton file and output file
    open(IN,$skeleton)    or die "Opening $skeleton: $!\n";
    open(OUT,">$outfile") or die "Opening $outfile: $!\n";

# loop over lines in "skeleton.F" and overwrite where neccessary
    while(<IN>) {
#  Preserve case for lowercase
	s/procname/$name/g;
#  Map uppercase to uppercase
	s/PROCNAME/\U$name/g;
	s/John Doe/$author/;
	s/day-mon-xx/$now/;
#  Handle RCS keywords
	s/RCS\((\w+)\)/\$$1\$/g;
#  write out fortran comment lines without upcasing
	if (/^c/ || /^C/ || /^\*/) {
	    print OUT $_;
	}
	elsif( /^lowcap/ ) {
	    # write out in lower case when flagged by "lowcap"
	    s/lowcap//;
	    print OUT "\L$_";
	}
	else {
	    print OUT $_;
	}
    }
    close(IN);   
    close(OUT);
    if ($flag =~ /[bpC]/) {
	chmod(0755,$outfile);
    }
}
}

# help package
sub wrt_help {

    print <<'ENDHELP';
mkfortproc  h: simple little script to make fortran processor skeletons
mkfortproc  h:
mkfortproc  h:  execution:  mkfortproc fortranprocname  
mkfortproc  h: 
mkfortproc  h:  output:  fortranprocname/
mkfortproc  h:                         README.MyFortProc
mkfortproc  h:                         Makefile
mkfortproc  h:                         fortranprocname/fortranprocname.h
mkfortproc  h:                                       Template/
mkfortproc  h:                         Class/fortranprocname.cc
mkfortproc  h:                               fortranprocname_DONT_TOUCH.cc
mkfortproc  h:                         Fortran/
mkfortproc  h:                               fortranprocname_beginRun.F
mkfortproc  h:                               fortranprocname_endRun.F
mkfortproc  h:                               fortranprocname_event.F
mkfortproc  h:                               fortranprocname_hist_book.F
mkfortproc  h:                               fortranprocname_initialize.F
mkfortproc  h:                               fortranprocname_terminate.F         
mkfortproc  h:                         Instantiate/
mkfortproc  h:                         Doc/
mkfortproc  h:                         Test/
mkfortproc  h:  required input:
mkfortproc  h: 
mkfortproc  h:  fortranprocname = name of the processor
mkfortproc  h: 
mkfortproc  h:  optional input:
mkfortproc  h: 
mkfortproc  h:  none
mkfortproc  h: 
mkfortproc  h:  example:
mkfortproc  h:  mkfortproc MyFortProc 
mkfortproc  h:        --> write  MyFortProc/
mkfortproc  h:                         README.MyFortProc
mkfortproc  h:                         Makefile
mkfortproc  h:                         MyFortProc/MyFortProc.h
mkfortproc  h:                                       Template/
mkfortproc  h:                         Class/MyFortProc.cc
mkfortproc  h:                               MyFortProc_DONT_TOUCH.cc
mkfortproc  h:                         Fortran/
mkfortproc  h:                               MyFortProc_beginRun.F
mkfortproc  h:                               MyFortProc_endRun.F
mkfortproc  h:                               MyFortProc_event.F
mkfortproc  h:                               MyFortProc_hist_book.F
mkfortproc  h:                               MyFortProc_initialize.F
mkfortproc  h:                               MyFortProc_terminate.F         
mkfortproc  h:                         Instantiate/
mkfortproc  h:                         Doc/
mkfortproc  h:                         Test/
ENDHELP

    print "mkfortproc  Q: Please enter processor name: ";
    $ARGV[0] = <STDIN>;
    chop($ARGV[0]);
}
