#!/usr/local/bin/perl
#
# $Id: mkprod,v 1.11 2002/10/16 18:33:59 cdj Exp $
###########################################################################
#  simple little script to make producer skeletons
# 
#  execution:  mkprod producername  
# 
#  output:  producername/
#                         Makefile
#                         producername/producername.h
#                                       Template/
#                         Class/producername.cc
#                               producername_DONT_TOUCH.cc
#                         Instantiate/
#                         Doc/
#                         Test/
#  required input:
# 
#  producername = name of the producer
# 
#  optional input:
# 
#  none
# 
#  example:
#  mkprod MyProducer 
#        --> write  MyProducer/
#                               Makefile
#                               MyProducer/MyProducer.h
#                               MyProducer/Template/
#                               Class/MyProducer.cc
#                               Class/MyProducer_DONT_TOUCH.cc
#                               Instantiate/
#                               Doc/
#                               Test/
#  
#   the script tries to read in
#   a filename .tmpl in users HOME directory which contains the following lines
#             First : your first name
#             Last : your last name
#   if .tmpl is not found and firstname and lastname are blank the
#   enviroment variable LOGNAME is used to obtain the "real life" name
#   from the output of finger.
#
#   Enviroment variable PROC_SCRIPT may point to a directory that
#   contains the skeleton files.
#
#   mkprod will not overwrite existing files
#
#   Skeleton Keywords (Case matters):
#      prodname  :  overwritten with routine name
#      John Doe  :  overwritten with author's name
#      day-mon-xx:  overwritten with todays date
#      RCS(key)  :  becomes $key$
#
#   author of the script: Martin Lohner
#                         (based on mkproc)
#   
###########################################################################


#  if the routine name is blank, 'h' or '?' go to help
if ($ARGV[0] !~ /\w/ 
 || $ARGV[0] eq "\?" 
 || $ARGV[0] eq "h" 
 || $ARGV[0] eq "-h" 
 || $ARGV[0] eq "-help" ) {
   &wrt_help; 
}

$author1 = "\u$ARGV[2]";
$author2 = "\u$ARGV[3]";

# environment variables
$home = $ENV{"HOME"};
$c3_inc = $ENV{"C3_INC"};
$c_gmake = $ENV{"C3_GMAKE"};

#  skeleton file directory
# eventually will use $skel_dir = $ENV{"CMH_SCRIPT"};
if (!$skel_dir) {
    $CLEO3 = $ENV{"C3_CVSSRC"};
    $skel_dir = "$CLEO3/Skeletons";
}

# get name
($name, $ext) = split(/\./, $ARGV[0]);

# Names must begin with capital letters.
if ( ! ( $name =~ /^[A-Z]/ ) )
{
    print "
mkprod  E: Producer names must begin with capital letters, and each
mkprod  E: separate 'word' in the name should also start with a capital
mkprod  E: letter.  For example, MyTrackingTestProd is a valid name,
mkprod  E: but myTrackingTestProd and MyTrackingtestProd are not.\n\n";
    exit 1;
}

# Names must end with 'Prod'.
$endsInProd = ( $name =~ /Prod$/ );
$endsInProducer = ( $name =~ /Producer$/ );
if ( ! ( $endsInProd || $endsInProducer ) )
{
    print "mkprod  N: Producer names should end with 'Prod'.\n";
    print "mkprod  N: I've added it to the name you supplied for you.\n";
    $name .= "Prod";
}
elsif ( $endsInProducer )
{
    print "mkprod  W: Producer names should end with 'Prod', not 'Producer'.\n"
	;
    print "mkprod  W: This will be changed for you automatically.\n";
    print "mkprod  W: Don't let it happen again.\n";
    $name =~ s/Producer$/Prod/;
}

#create the directories
mkdir("$name", 0777) || die "can not make dir $name";
mkdir("$name/$name", 0777) || die "can not make dir $name/$name";
mkdir("$name/$name/Template", 0777) || die "can not make dir $name/$name/Template";
mkdir("$name/Class", 0777) || die "can not make dir $name/Class";
mkdir("$name/Instantiate", 0777) || die "can not make dir $name/Instantiate";
mkdir("$name/Test", 0777) || die "can not make dir $name/Test";
mkdir("$name/Doc", 0777) || die "can not make dir $name/Doc";

$skeleton = "$skel_dir/Producer/README.producer";
$outfile = "$name/" . README . '.' . $name;
&make_file($skeleton, $outfile);

$skeleton = "$skel_dir/Producer/producer.h";
$outfile = "$name/$name/" . $name . '.h';
&make_file($skeleton, $outfile);

$skeleton = "$skel_dir/Producer/producer.cc";
$outfile = "$name/Class/" . $name . '.cc';
&make_file($skeleton, $outfile);

$skeleton = "$skel_dir/Producer/producer_DONT_TOUCH.cc";
$outfile = "$name/Class/" . $name . '_DONT_TOUCH.cc';
&make_file($skeleton, $outfile);

$skeleton = "$c_gmake/M.processor";
$outfile = "$name/Makefile";
&copy_file($skeleton, $outfile);


# copy file
sub copy_file {
# first argument is file to be copied
$skeleton = $_[0]; 
# second argument is the name of the new file
$outfile = $_[1];

if (-s "$outfile") {
    print "mkprod  W: $outfile FILE ALREADY EXISTS WILL NOT OVERWRITE!!\n";
    print "mkprod  W: *****************************************************\n";
} else {

#   write out some stuff to the screen
    print "mkprod  I: copying file $skeleton to $outfile\n";

#open the skeleton file and output file
    open(IN,$skeleton)    or die "Opening $skeleton: $!\n";
    open(OUT,">$outfile") or die "Opening $outfile: $!\n";

# loop over lines in "skeleton.F" and overwrite where neccessary
    while(<IN>) {
	print OUT $_;
    }
    close(IN);   
    close(OUT);
}
}


# generate file
sub make_file {
# first argument is the skeleton file to use
$skeleton = $_[0];
# second argument is the name of the output file
$outfile = $_[1];

if (-s "$outfile") {
    print "mkprod  W: $outfile FILE ALREADY EXISTS WILL NOT OVERWRITE!!\n";
    print "mkprod  W: *****************************************************\n";
} else {
#  get the current date
    $now = `date`;
    chop($now);

# get authors name from $HOME/.tmpl file

    $afrom = "command line";
    if ($author1 eq "" && -s "$home/.tmpl") {
	open(IN,"$home/.tmpl");
	$afrom = "users .tmpl file";
	while(<IN>) {
	    if (/First\w*/) {
		@words = split(/:/, $_);
		$author1 = $words[1]; 
		chop($author1);
	    } elsif (/Last\w*/) {
		@words = split(/:/, $_);
		$author2 = $words[1];
		chop($author2);
	    }
	}
	close(IN);
	$author = "$author1 $author2";
    }
#
# if author is still blank fill it in with REAL LIFE name in finger output
#
    if ($author1 eq "") {
	$author1 = $ENV{"LOGNAME"};
	foreach $_ (`finger -m "$author1"`) {
	    if (/Login n\w*/) {
		@words = split(/: /, $_);
		$author = $words[2];
		chop($author);
		$afrom = "the output finger cmnd";
	    }
	}
    }
#   write out some stuff to the screen
    print "mkprod  I: using skeleton: $skeleton \n";
    print "mkprod  I: authors name is: $author, determined by $afrom \n";
    print "mkprod  I: creating file: $outfile \n";

#open the skeleton file and output file
    open(IN,$skeleton)    or die "Opening $skeleton: $!\n";
    open(OUT,">$outfile") or die "Opening $outfile: $!\n";

# loop over lines in "skeleton.F" and overwrite where neccessary
    while(<IN>) {
#  Preserve case for lowercase
	s/prodname/$name/g;
#  Map uppercase to uppercase
	s/PRODNAME/\U$name/g;
	s/John Doe/$author/;
	s/day-mon-xx/$now/;
#  Handle RCS keywords
	s/RCS\((\w+)\)/\$$1\$/g;
#  write out fortran comment lines without upcasing
	if (/^c/ || /^C/ || /^\*/) {
	    print OUT $_;
	} else {
	    print OUT $_;
	}
    }
    close(IN);   
    close(OUT);
    if ($flag =~ /[bpC]/) {
	chmod(0755,$outfile);
    }
}
}

# help package
sub wrt_help {

    print <<'ENDHELP';
mkprod  h: simple little script to make producer skeletons
mkprod  h:
mkprod  h: execution:  mkprod producername  
mkprod  h:
mkprod  h: output:  producername/
mkprod  h:                       Makefile
mkprod  h:                       producername/producername.h
mkprod  h:                                    Template/
mkprod  h:                       Class/producername.cc
mkprod  h:                             producername_DONT_TOUCH.cc
mkprod  h:                       Instantiate/
mkprod  h:                       Doc/
mkprod  h:                       Test/
mkprod  h:
mkprod  h: required input:
mkprod  h:
mkprod  h: producername = name of the producer
mkprod  h:
mkprod  h: optional input:
mkprod  h:
mkprod  h: none
mkprod  h:
mkprod  h: example:
mkprod  h: mkprod MyProducer 
mkprod  h:       --> write  MyProducer/
mkprod  h:                              Makefile
mkprod  h:                              MyProducer/MyProducer.h
mkprod  h:                              MyProducer/Template/
mkprod  h:                              Class/MyProducer.cc
mkprod  h:                              Class/MyProducer_DONT_TOUCH.cc
mkprod  h:                              Instantiate/
mkprod  h:                              Doc/
mkprod  h:                              Test/
ENDHELP

    print "mkprod  Q: Please enter producer name: ";
    $ARGV[0] = <STDIN>;
    chop($ARGV[0]);
}
